### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MCprotein** [MBTI-Inside/server#16]
## github actions
- [ ] build - branch 선택 기본적으로 존재하는 칸 사용
- [ ] deploy - appleboy package -> cli 변경
- [ ] 테스트 코드 작성
- [ ] 자동배포 설정
- [ ] string <-> ObjectId 자동 변환 설정
- [ ] node stream 코드 rxjs로 변경
